pretty-print = "never"
xml-namespace = false
ignore-unknown-commands = true
allow-unreliable-rendering = true
unicode-substitution = "conventional"

[macros]
mathexclam = '!'
mathoctothorpe = '\#'
mathdollar = '\$'
mathpercent = '\%'
mathampersand = '\&'
mathplus = '+'
mathcomma = ','
mathperiod = '.'

ocirc = '\mathring'

mupAlpha = '\Alpha'
mupBeta = '\Beta'
mupGamma = '\Gamma'
mupDelta = '\Delta'
mupEpsilon = '\Epsilon'
mupZeta = '\Zeta'
mupEta = '\Eta'
mupTheta = '\Theta'
mupIota = '\Iota'
mupKappa = '\Kappa'
mupLambda = '\Lambda'
mupMu = '\Mu'
mupNu = '\Nu'
mupXi = '\Xi'
mupOmicron = '\Omicron'
mupPi = '\Pi'
mupRho = '\Rho'
mupSigma = '\Sigma'
mupTau = '\Tau'
mupUpsilon = '\Upsilon'
mupPhi = '\Phi'
mupChi = '\Chi'
mupPsi = '\Psi'
mupOmega = '\Omega'
mupalpha = '\mathrm\alpha'
mupbeta = '\mathrm\beta'
mupgamma = '\mathrm\gamma'
mupdelta = '\mathrm\delta'
mupvarepsilon = '\mathrm\varepsilon'
mupzeta = '\mathrm\zeta'
mupeta = '\mathrm\eta'
muptheta = '\mathrm\theta'
mupiota = '\mathrm\iota'
mupkappa = '\mathrm\kappa'
muplambda = '\mathrm\lambda'
mupmu = '\mathrm\mu'
mupnu = '\mathrm\nu'
mupxi = '\mathrm\xi'
mupomicron = '\mathrm\omicron'
muppi = '\mathrm\pi'
muprho = '\mathrm\rho'
mupvarsigma = '\mathrm\varsigma'
mupsigma = '\mathrm\sigma'
muptau = '\mathrm\tau'
mupupsilon = '\mathrm\upsilon'
mupvarphi = '\mathrm\varphi'
mupchi = '\mathrm\chi'
muppsi = '\mathrm\psi'
mupomega = '\mathrm\omega'
mupvartheta = '\mathrm\vartheta'
mupphi = '\mathrm\phi'
mupvarpi = '\mathrm\varpi'
# upDigamma = '\Digamma'
updigamma = '\digamma'
mupvarkappa = '\mathrm\varkappa'
mupvarrho = '\mathrm\varrho'
mupvarTheta = '\mathrm\varTheta'
mupepsilon = '\mathrm\epsilon'
upbackepsilon = '\backepsilon'

# dprime = '″'
# trprime = '‴'
# backdprime = '‶'
# backtrprime = '‷'

# qprime = '⁗'

longmapsfrom = '⟻'
Longmapsfrom = '⟽'
Longmapsto = '⟾'
longrightsquigarrow = '⟿'
