use super::attribute::{Accent, DisplayStyle, MathVariant, TextTransform};
use super::ops::{self, Op};

const NORMAL: Option<MathVariant> = Some(MathVariant::Normal);

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Null,
    EOF,
    Begin,
    End,
    Ampersand,
    NewLine,
    Left,
    Right,
    Middle,
    Paren(Op),
    LBrace,
    RBrace,
    Frac(Option<DisplayStyle>),
    Underscore,
    Circumflex,
    Binom(Option<DisplayStyle>),
    Overset,
    Underset,
    Overbrace(Op),
    Underbrace(Op),
    Sqrt,
    Integral(Op),
    Lim(&'static str),
    Space(f32),
    NonBreakingSpace,
    Style(TextTransform),
    NormalVariant,
    Big(&'static str),
    Over(Op, Accent),
    Under(Op, Accent),
    Operator(Op),
    Colon,
    ParenPlaceholder,
    BigOp(Op),
    Letter(char, Option<MathVariant>),
    Number(String),
    Function(&'static str),
    OperatorName,
    Slashed,
    Text,
    Command(String),
}

impl Token {
    pub(crate) fn acts_on_a_digit(&self) -> bool {
        matches!(
            self,
            Token::Sqrt | Token::Frac(_) | Token::Binom(_) | Token::Style(_)
        )
    }

    pub fn from_command(command: &str) -> Token {
        match command {
            "mathrm" => Token::NormalVariant,
            "textit" => Token::Style(TextTransform::Italic),
            "mathit" => Token::Style(TextTransform::Italic),
            "mathcal" => Token::Style(TextTransform::Script),
            "textbf" => Token::Style(TextTransform::Bold),
            "mathbf" => Token::Style(TextTransform::Bold),
            "bm" => Token::Style(TextTransform::BoldItalic),
            "symbf" => Token::Style(TextTransform::BoldItalic),
            "mathbb" => Token::Style(TextTransform::DoubleStruck),
            "mathfrak" => Token::Style(TextTransform::Fraktur),
            "mathscr" => Token::Style(TextTransform::Script),
            "mathsf" => Token::Style(TextTransform::SansSerif),
            "texttt" => Token::Style(TextTransform::Monospace),
            "boldsymbol" => Token::Style(TextTransform::BoldItalic),
            "text" => Token::Text,
            "sqrt" => Token::Sqrt,
            "frac" => Token::Frac(None),
            "tfrac" => Token::Frac(Some(DisplayStyle::False)),
            "dfrac" => Token::Frac(Some(DisplayStyle::True)),
            "left" => Token::Left,
            "right" => Token::Right,
            "middle" => Token::Middle,
            "begin" => Token::Begin,
            "end" => Token::End,
            "\\" => Token::NewLine,
            "binom" => Token::Binom(None),
            "tbinom" => Token::Binom(Some(DisplayStyle::False)),
            "dbinom" => Token::Binom(Some(DisplayStyle::True)),
            "overset" => Token::Overset,
            "underset" => Token::Underset,
            "overbrace" => Token::Overbrace(Op('\u{23de}')),
            "underbrace" => Token::Underbrace(Op('\u{23df}')),
            "overparen" => Token::Overbrace(Op('\u{23dc}')),
            "underparen" => Token::Underbrace(Op('\u{23dd}')),
            "overbracket" => Token::Overbrace(Op('\u{23b4}')),
            "underbracket" => Token::Underbrace(Op('\u{23b5}')),
            "!" => Token::Space(-3. / 18.),
            "," => Token::Space(3. / 18.),
            ":" => Token::Space(4. / 18.),
            ";" => Token::Space(5. / 18.),
            " " => Token::Space(1.),
            "quad" => Token::Space(1.),
            "qquad" => Token::Space(2.),
            "langle" => Token::Paren(Op('〈')),
            "rangle" => Token::Paren(Op('〉')),
            "{" => Token::Paren(ops::LEFT_CURLY_BRACKET),
            "}" => Token::Paren(ops::RIGHT_CURLY_BRACKET),
            "lceil" => Token::Paren(Op('⌈')),
            "rceil" => Token::Paren(Op('⌉')),
            "lfloor" => Token::Paren(Op('⌊')),
            "rfloor" => Token::Paren(Op('⌋')),
            "lgroup" => Token::Paren(Op('⦗')),
            "rgroup" => Token::Paren(Op('⦘')),
            "llbracket" => Token::Paren(Op('⟦')),
            "rrbracket" => Token::Paren(Op('⟧')),
            "lim" => Token::Lim("lim"),
            "liminf" => Token::Lim("lim inf"),
            "limsup" => Token::Lim("lim sup"),
            "min" => Token::Lim("min"),
            "max" => Token::Lim("max"),
            "inf" => Token::Lim("inf"),
            "sup" => Token::Lim("sup"),
            "int" => Token::Integral(Op('∫')),
            "iint" => Token::Integral(Op('∬')),
            "iiint" => Token::Integral(Op('∭')),
            "oint" => Token::Integral(Op('∮')),
            "dot" => Token::Over(Op('\u{02d9}'), Accent::True),
            "ddot" => Token::Over(Op('¨'), Accent::True),
            "bar" => Token::Over(Op('¯'), Accent::True),
            "hat" => Token::Over(Op('^'), Accent::True),
            "check" => Token::Over(Op('ˇ'), Accent::True),
            "breve" => Token::Over(Op('˘'), Accent::True),
            "acute" => Token::Over(Op('´'), Accent::True),
            "grave" => Token::Over(Op('`'), Accent::True),
            "tilde" => Token::Over(Op('~'), Accent::True),
            "vec" => Token::Over(Op('→'), Accent::True),
            "overline" => Token::Over(Op('_'), Accent::True),
            "underline" => Token::Under(Op('_'), Accent::True),
            "widehat" => Token::Over(Op('^'), Accent::True),
            "widetilde" => Token::Over(Op('~'), Accent::True),
            "overrightarrow" => Token::Over(Op('→'), Accent::True),
            "overleftarrow" => Token::Over(Op('←'), Accent::True),
            "sum" => Token::BigOp(Op('∑')),
            "prod" => Token::BigOp(Op('∏')),
            "coprod" => Token::BigOp(Op('∐')),
            "bigcap" => Token::BigOp(Op('⋂')),
            "bigcup" => Token::BigOp(Op('⋃')),
            "bigsqcup" => Token::BigOp(Op('⨆')),
            "bigvee" => Token::BigOp(Op('⋁')),
            "bigwedge" => Token::BigOp(Op('⋀')),
            "bigodot" => Token::BigOp(Op('⨀')),
            "bitotimes" => Token::BigOp(Op('⨂')),
            "bigoplus" => Token::BigOp(Op('⨁')),
            "biguplus" => Token::BigOp(Op('⨄')),
            "bigl" => Token::Big("1.2em"),
            "bigr" => Token::Big("1.2em"),
            "Bigl" => Token::Big("1.623em"),
            "Bigr" => Token::Big("1.623em"),
            "biggl" => Token::Big("2.047em"),
            "biggr" => Token::Big("2.047em"),
            "Biggl" => Token::Big("2.470em"),
            "Biggr" => Token::Big("2.470em"),
            // <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
            //   <semantics>
            //     <mrow>
            //         <mi>a</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="2.470em" minsize="2.470em">(</mo></ mrow>
            //         <mi>b</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="2.047em" minsize="2.047em">(</mo></mrow>
            //         <mi>c</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="1.623em" minsize="1.623em">(</mo></mrow>
            //         <mi>d</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="1.2em" minsize="1.2em">(</mo></mrow>
            //         <mi>e</mi>
            //         <mo stretchy="false">(</mo>
            //         <mi>f</mi>
            //         <mo>+</mo>
            //         <mi>g</mi>
            //         <mo stretchy="false">)</mo>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="1.2em" minsize="1.2em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="1.623em" minsize="1.623em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="2.047em" minsize="2.047em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="2.470em" minsize="2.470em">)</mo></mrow>
            //   </semantics>
            // </math>
            "sin" => Token::Function("sin"),
            "cos" => Token::Function("cos"),
            "tan" => Token::Function("tan"),
            "csc" => Token::Function("csc"),
            "sec" => Token::Function("sec"),
            "cot" => Token::Function("cot"),
            "arcsin" => Token::Function("arcsin"),
            "arccos" => Token::Function("arccos"),
            "arctan" => Token::Function("arctan"),
            "sinh" => Token::Function("sinh"),
            "cosh" => Token::Function("cosh"),
            "tanh" => Token::Function("tanh"),
            "coth" => Token::Function("coth"),
            "exp" => Token::Function("exp"),
            "ln" => Token::Function("ln"),
            "log" => Token::Function("log"),
            "erf" => Token::Function("erf"),
            "erfc" => Token::Function("erfc"),
            "arg" => Token::Function("arg"),
            "ker" => Token::Function("ker"),
            "dim" => Token::Function("dim"),
            "det" => Token::Function("det"),
            "wp" => Token::Function("℘"),
            "operatorname" => Token::OperatorName,
            "Alpha" => Token::Letter('Α', NORMAL),
            "alpha" => Token::Letter('α', None),
            "Beta" => Token::Letter('Β', NORMAL),
            "beta" => Token::Letter('β', None),
            "Gamma" => Token::Letter('Γ', NORMAL),
            "gamma" => Token::Letter('γ', None),
            "digamma" => Token::Letter('ϝ', None),
            "Delta" => Token::Letter('Δ', NORMAL),
            "delta" => Token::Letter('δ', None),
            "Epsilon" => Token::Letter('Ε', NORMAL),
            "epsilon" => Token::Letter('ϵ', None),
            "varepsilon" => Token::Letter('ε', None),
            "Zeta" => Token::Letter('Ζ', NORMAL),
            "zeta" => Token::Letter('ζ', None),
            "Eta" => Token::Letter('Η', NORMAL),
            "eta" => Token::Letter('η', None),
            "Theta" => Token::Letter('Θ', NORMAL),
            "theta" => Token::Letter('θ', None),
            "vartheta" => Token::Letter('ϑ', None),
            "Iota" => Token::Letter('Ι', NORMAL),
            "iota" => Token::Letter('ι', None),
            "Kappa" => Token::Letter('Κ', NORMAL),
            "kappa" => Token::Letter('κ', None),
            "Lambda" => Token::Letter('Λ', NORMAL),
            "lambda" => Token::Letter('λ', None),
            "Mu" => Token::Letter('Μ', NORMAL),
            "mu" => Token::Letter('μ', None),
            "Nu" => Token::Letter('Ν', NORMAL),
            "nu" => Token::Letter('ν', None),
            "Xi" => Token::Letter('Ξ', NORMAL),
            "xi" => Token::Letter('ξ', None),
            "Omicron" => Token::Letter('Ο', NORMAL),
            "omicron" => Token::Letter('ο', None),
            "Pi" => Token::Letter('Π', NORMAL),
            "pi" => Token::Letter('π', None),
            "varpi" => Token::Letter('ϖ', None),
            "Rho" => Token::Letter('Ρ', NORMAL),
            "rho" => Token::Letter('ρ', None),
            "varrho" => Token::Letter('ϱ', None),
            "Sigma" => Token::Letter('Σ', NORMAL),
            "sigma" => Token::Letter('σ', None),
            "varsigma" => Token::Letter('ς', None),
            "Tau" => Token::Letter('Τ', NORMAL),
            "tau" => Token::Letter('τ', None),
            "Upsilon" => Token::Letter('Υ', NORMAL),
            "upsilon" => Token::Letter('υ', None),
            "Phi" => Token::Letter('Φ', NORMAL),
            "phi" => Token::Letter('ϕ', None),
            "varphi" => Token::Letter('φ', None),
            "Chi" => Token::Letter('Χ', NORMAL),
            "chi" => Token::Letter('χ', None),
            "Psi" => Token::Letter('Ψ', NORMAL),
            "psi" => Token::Letter('ψ', None),
            "Omega" => Token::Letter('Ω', NORMAL),
            "omega" => Token::Letter('ω', None),
            "aleph" => Token::Letter('ℵ', NORMAL),
            "beth" => Token::Letter('ℶ', NORMAL),
            "gimel" => Token::Letter('ℷ', NORMAL),
            "daleth" => Token::Letter('ℸ', NORMAL),
            "A" => Token::Letter('Å', NORMAL),
            "a" => Token::Letter('å', NORMAL),
            "AE" => Token::Letter('Æ', NORMAL),
            "ae" => Token::Letter('æ', NORMAL),
            "DH" => Token::Letter('Ð', NORMAL),
            "dh" => Token::Letter('ð', NORMAL),
            "dj" => Token::Letter('đ', NORMAL),
            "L" => Token::Letter('Ł', NORMAL),
            "l" => Token::Letter('ł', NORMAL),
            "NG" => Token::Letter('Ŋ', NORMAL),
            "ng" => Token::Letter('ŋ', NORMAL),
            "O" => Token::Letter('Ø', NORMAL),
            "o" => Token::Letter('ø', NORMAL),
            "OE" => Token::Letter('Œ', NORMAL),
            "oe" => Token::Letter('œ', NORMAL),
            "ss" => Token::Letter('ß', NORMAL),
            "TH" => Token::Letter('Þ', NORMAL),
            "th" => Token::Letter('þ', NORMAL),
            "imath" => Token::Letter('ı', None),
            "jmath" => Token::Letter('ȷ', None),
            "ell" => Token::Letter('ℓ', None),
            "hbar" => Token::Letter('ℏ', None),
            "hslash" => Token::Letter('ℏ', None),
            "infty" => Token::Letter('∞', NORMAL),
            "mho" => Token::Letter('℧', NORMAL),
            "Finv" => Token::Letter('Ⅎ', NORMAL),
            "Re" => Token::Letter('ℜ', NORMAL),
            "Im" => Token::Letter('ℑ', NORMAL),
            "complement" => Token::Letter('∁', NORMAL),
            "emptyset" => Token::Letter('∅', NORMAL),
            "varnothing" => Token::Letter('ø', None),
            "therefore" => Token::Letter('∴', NORMAL),
            "because" => Token::Letter('∵', NORMAL),
            "Diamond" => Token::Letter('◊', NORMAL),
            "Box" => Token::Letter('◻', NORMAL),
            "triangle" => Token::Letter('△', NORMAL),
            "angle" => Token::Letter('∠', NORMAL),
            "dagger" => Token::Letter('†', NORMAL),
            "dag" => Token::Letter('†', NORMAL),
            "Dagger" => Token::Letter('‡', NORMAL),
            "ddag" => Token::Letter('‡', NORMAL),
            "And" => Token::Letter('&', NORMAL),
            "eth" => Token::Letter('ð', NORMAL),
            "S" => Token::Letter('§', NORMAL),
            "P" => Token::Letter('¶', NORMAL),
            "%" => Token::Letter('%', NORMAL),
            "_" => Token::Letter('_', NORMAL),
            "&" => Token::Letter('&', NORMAL),
            "#" => Token::Letter('#', NORMAL),
            "$" => Token::Letter('$', NORMAL),
            "copyright" => Token::Letter('©', NORMAL),
            "checkmark" => Token::Letter('✓', NORMAL),
            "circledR" => Token::Letter('Ⓡ', NORMAL),
            "maltese" => Token::Letter('✠', NORMAL),
            "colon" => Token::Letter(':', NORMAL),
            "bigtriangleup" => Token::Letter('△', NORMAL),
            "sphericalangle" => Token::Letter('∢', NORMAL),
            "square" => Token::Letter('□', NORMAL),
            "lozenge" => Token::Letter('◊', NORMAL),
            "diamondsuit" => Token::Letter('♢', NORMAL),
            "heartsuit" => Token::Letter('♡', NORMAL),
            "clubsuit" => Token::Letter('♣', NORMAL),
            "spadesuit" => Token::Letter('♠', NORMAL),
            "Game" => Token::Letter('⅁', NORMAL),
            "flat" => Token::Letter('♭', NORMAL),
            "natural" => Token::Letter('♮', NORMAL),
            "sharp" => Token::Letter('♯', NORMAL),
            "pounds" => Token::Letter('£', NORMAL),
            "textyen" => Token::Letter('¥', NORMAL),
            "euro" => Token::Letter('€', NORMAL),
            "rupee" => Token::Letter('₹', NORMAL),
            "sun" => Token::Letter('☼', NORMAL),
            "mercury" => Token::Letter('☿', NORMAL),
            "venus" => Token::Letter('♀', NORMAL),
            "earth" => Token::Letter('♁', NORMAL),
            "mars" => Token::Letter('♂', NORMAL),
            "jupiter" => Token::Letter('♃', NORMAL),
            "saturn" => Token::Letter('♄', NORMAL),
            "uranus" => Token::Letter('♅', NORMAL),
            "neptune" => Token::Letter('♆', NORMAL),
            "astrosun" => Token::Letter('☉', NORMAL),
            "ascnode" => Token::Letter('☊', NORMAL),
            "times" => Token::Operator(ops::TIMES),
            "oplus" => Token::Operator(Op('⊕')),
            "ominus" => Token::Operator(Op('⊖')),
            "otimes" => Token::Operator(Op('⊗')),
            "oslash" => Token::Operator(Op('⊘')),
            "odot" => Token::Operator(Op('⊙')),
            "bigcirc" => Token::Operator(Op('◯')),
            "amalg" => Token::Operator(Op('⨿')),
            "pm" => Token::Operator(Op('±')),
            "mp" => Token::Operator(Op('∓')),
            "cdot" => Token::Operator(Op('·')),
            "cdots" => Token::Operator(Op('⋯')),
            "vdots" => Token::Operator(Op('⋮')),
            "ldots" => Token::Operator(Op('…')),
            "ddots" => Token::Operator(Op('⋱')),
            "circ" => Token::Operator(Op('∘')),
            "bullet" => Token::Operator(Op('∙')),
            "star" => Token::Operator(Op('⋆')),
            "div" => Token::Operator(Op('÷')),
            "lnot" => Token::Operator(Op('¬')),
            "neg" => Token::Operator(Op('¬')),
            "land" => Token::Operator(Op('∧')),
            "lor" => Token::Operator(Op('∨')),
            "sim" => Token::Operator(Op('∼')),
            "simeq" => Token::Operator(Op('≃')),
            "nsim" => Token::Operator(Op('≁')),
            "cong" => Token::Operator(Op('≅')),
            "approx" => Token::Operator(Op('≈')),
            "ne" => Token::Operator(Op('≠')),
            "neq" => Token::Operator(Op('≠')),
            "equiv" => Token::Operator(Op('≡')),
            "nequiv" => Token::Operator(Op('≢')),
            "prec" => Token::Operator(Op('≺')),
            "succ" => Token::Operator(Op('≻')),
            "preceq" => Token::Operator(Op('⪯')),
            "succeq" => Token::Operator(Op('⪰')),
            "dashv" => Token::Operator(Op('⊣')),
            "asymp" => Token::Operator(Op('≍')),
            "doteq" => Token::Operator(Op('≐')),
            "propto" => Token::Operator(Op('∝')),
            "barwedge" => Token::Operator(Op('⊼')),
            "ltimes" => Token::Operator(Op('⋉')),
            "rtimes" => Token::Operator(Op('⋊')),
            "Join" => Token::Operator(Op('⋈')),
            "lhd" => Token::Operator(Op('⊲')),
            "rhd" => Token::Operator(Op('⊳')),
            "unlhd" => Token::Operator(Op('⊴')),
            "unrhd" => Token::Operator(Op('⊵')),
            "vee" => Token::Operator(Op('∨')),
            "uplus" => Token::Operator(Op('⊎')),
            "wedge" => Token::Operator(Op('∧')),
            "boxdot" => Token::Operator(Op('⊡')),
            "boxplus" => Token::Operator(Op('⊞')),
            "boxminus" => Token::Operator(Op('⊟')),
            "boxtimes" => Token::Operator(Op('⊠')),
            "boxbox" => Token::Operator(Op('⧈')),
            "boxslash" => Token::Operator(Op('⧄')),
            "boxbslash" => Token::Operator(Op('⧅')),
            "Cap" => Token::Operator(Op('⋒')),
            "Cup" => Token::Operator(Op('⋓')),
            "centerdot" => Token::Operator(Op('∙')),
            "circledast" => Token::Operator(Op('⊛')),
            "circledcirc" => Token::Operator(Op('⊚')),
            "circleddash" => Token::Operator(Op('⊝')),
            "curlyvee" => Token::Operator(Op('⋎')),
            "curlywedge" => Token::Operator(Op('⋏')),
            "dotplus" => Token::Operator(Op('∔')),
            "intercal" => Token::Operator(Op('⊺')),
            "divideontimes" => Token::Operator(Op('⋇')),
            "leftthreetimes" => Token::Operator(Op('⋋')),
            "rightthreetimes" => Token::Operator(Op('⋌')),
            "smallsetminus" => Token::Operator(Op('﹨')),
            "triangledown" => Token::Operator(Op('▽')),
            "triangleleft" => Token::Operator(Op('◁')),
            "triangleright" => Token::Operator(Op('▷')),
            "vartriangle" => Token::Operator(Op('△')),
            "veebar" => Token::Operator(Op('⊻')),
            "cap" => Token::Operator(Op('∩')),
            "cup" => Token::Operator(Op('∪')),
            "mid" => Token::Operator(Op('\u{2223}')),
            "nmid" => Token::Operator(Op('\u{2224}')),
            "|" => Token::Paren(Op('‖')),
            "parallel" => Token::Operator(Op('∥')),
            "perp" => Token::Operator(Op('⊥')),
            "forall" => Token::Operator(Op('∀')),
            "exists" => Token::Operator(Op('∃')),
            "nexists" => Token::Operator(Op('∄')),
            "lt" => Token::Operator(Op('<')),
            "gt" => Token::Operator(Op('>')),
            "leq" => Token::Operator(Op('≤')),
            "geq" => Token::Operator(Op('≥')),
            "ll" => Token::Operator(Op('≪')),
            "gg" => Token::Operator(Op('≫')),
            "lessapprox" => Token::Operator(Op('⪅')),
            "lesssim" => Token::Operator(Op('≲')),
            "eqslantless" => Token::Operator(Op('⪕')),
            "leqslant" => Token::Operator(Op('⩽')),
            "leqq" => Token::Operator(Op('≦')),
            "geqq" => Token::Operator(Op('≧')),
            "geqslant" => Token::Operator(Op('⩾')),
            "eqslantgtr" => Token::Operator(Op('⪖')),
            "gtrsim" => Token::Operator(Op('≳')),
            "gtrapprox" => Token::Operator(Op('⪆')),
            "approxeq" => Token::Operator(Op('≊')),
            "lessdot" => Token::Operator(Op('⋖')),
            "lll" => Token::Operator(Op('⋘')),
            "lessgtr" => Token::Operator(Op('≶')),
            "lesseqgtr" => Token::Operator(Op('⋚')),
            "lesseqqgtr" => Token::Operator(Op('⪋')),
            "doteqdot" => Token::Operator(Op('≑')),
            "risingdotseq" => Token::Operator(Op('≓')),
            "leftarrow" => Token::Operator(Op('←')),
            "gets" => Token::Operator(Op('←')),
            "rightarrow" => Token::Operator(Op('→')),
            "to" => Token::Operator(Op('→')),
            "nleftarrow" => Token::Operator(Op('↚')),
            "nrightarrow" => Token::Operator(Op('↛')),
            "leftrightarrow" => Token::Operator(Op('↔')),
            "nleftrightarrow" => Token::Operator(Op('↮')),
            "longleftarrow" => Token::Operator(Op('⟵')),
            "longrightarrow" => Token::Operator(Op('⟶')),
            "longleftrightarrow" => Token::Operator(Op('⟷')),
            "Leftarrow" => Token::Operator(Op('⇐')),
            "Rightarrow" => Token::Operator(Op('⇒')),
            "nLeftarrow" => Token::Operator(Op('⇍')),
            "nRightarrow" => Token::Operator(Op('⇏')),
            "Leftrightarrow" => Token::Operator(Op('⇔')),
            "nLeftrightarrow" => Token::Operator(Op('⇎')),
            "Longleftarrow" => Token::Operator(Op('⟸')),
            "impliedby" => Token::Operator(Op('⟸')),
            "Longrightarrow" => Token::Operator(Op('⟹')),
            "implies" => Token::Operator(Op('⟹')),
            "Longleftrightarrow" => Token::Operator(Op('⟺')),
            "iff" => Token::Operator(Op('⟺')),
            "uparrow" => Token::Operator(Op('↑')),
            "downarrow" => Token::Operator(Op('↓')),
            "updownarrow" => Token::Operator(Op('↕')),
            "Uparrow" => Token::Operator(Op('⇑')),
            "Downarrow" => Token::Operator(Op('⇓')),
            "Updownarrow" => Token::Operator(Op('⇕')),
            "nearrow" => Token::Operator(Op('↗')),
            "searrow" => Token::Operator(Op('↘')),
            "swarrow" => Token::Operator(Op('↙')),
            "nwarrow" => Token::Operator(Op('↖')),
            "rightharpoonup" => Token::Operator(Op('⇀')),
            "rightharpoondown" => Token::Operator(Op('⇁')),
            "leftharpoonup" => Token::Operator(Op('↼')),
            "leftharpoondown" => Token::Operator(Op('↽')),
            "upharpoonleft" => Token::Operator(Op('↿')),
            "upharpoonright" => Token::Operator(Op('↾')),
            "downharpoonleft" => Token::Operator(Op('⇃')),
            "downharpoonright" => Token::Operator(Op('⇂')),
            "rightleftharpoons" => Token::Operator(Op('⇌')),
            "leftrightharpoons" => Token::Operator(Op('⇋')),
            "curvearrowleft" => Token::Operator(Op('↶')),
            "circlearrowleft" => Token::Operator(Op('↺')),
            "Lsh" => Token::Operator(Op('↰')),
            "upuparrows" => Token::Operator(Op('⇈')),
            "rightrightarrows" => Token::Operator(Op('⇉')),
            "rightleftarrows" => Token::Operator(Op('⇄')),
            "Rrightarrow" => Token::Operator(Op('⇛')),
            "rightarrowtail" => Token::Operator(Op('↣')),
            "looparrowright" => Token::Operator(Op('↬')),
            "curvearrowright" => Token::Operator(Op('↷')),
            "circlearrowright" => Token::Operator(Op('↻')),
            "Rsh" => Token::Operator(Op('↱')),
            "downdownarrows" => Token::Operator(Op('⇊')),
            "leftleftarrows" => Token::Operator(Op('⇇')),
            "leftrightarrows" => Token::Operator(Op('⇆')),
            "Lleftarrow" => Token::Operator(Op('⇚')),
            "leftarrowtail" => Token::Operator(Op('↢')),
            "looparrowleft" => Token::Operator(Op('↫')),
            "mapsto" => Token::Operator(Op('↦')),
            "longmapsto" => Token::Operator(Op('⟼')),
            "hookrightarrow" => Token::Operator(Op('↪')),
            "hookleftarrow" => Token::Operator(Op('↩')),
            "multimap" => Token::Operator(Op('⊸')),
            "leftrightsquigarrow" => Token::Operator(Op('↭')),
            "rightsquigarrow" => Token::Operator(Op('⇝')),
            "lightning" => Token::Operator(Op('↯')),
            "Yleft" => Token::Operator(Op('⤙')),
            "Yright" => Token::Operator(Op('⤚')),
            "in" => Token::Operator(Op('∈')),
            "ni" => Token::Operator(Op('\u{2209}')),
            "notin" => Token::Operator(Op('\u{2209}')),
            "subset" => Token::Operator(Op('\u{2282}')),
            "supset" => Token::Operator(Op('\u{2283}')),
            "subseteq" => Token::Operator(Op('\u{2286}')),
            "supseteq" => Token::Operator(Op('\u{2287}')),
            "nsubseteq" => Token::Operator(Op('\u{2288}')),
            "nsupseteq" => Token::Operator(Op('\u{2289}')),
            "subsetneq" => Token::Operator(Op('\u{228a}')),
            "supsetneq" => Token::Operator(Op('\u{228b}')),
            "sqsubset" => Token::Operator(Op('⊏')),
            "sqsubseteq" => Token::Operator(Op('⊑')),
            "sqsupset" => Token::Operator(Op('⊐')),
            "sqsupseteq" => Token::Operator(Op('⊒')),
            "sqcap" => Token::Operator(Op('⊓')),
            "sqcup" => Token::Operator(Op('⊔')),
            "setminus" => Token::Operator(Op('∖')),
            "partial" => Token::Letter('∂', None),
            "nabla" => Token::Operator(Op('∇')),
            "smile" => Token::Operator(Op('⌣')),
            "from" => Token::Operator(Op('⌢')),
            "wr" => Token::Operator(Op('≀')),
            "bot" => Token::Operator(Op('⊥')),
            "top" => Token::Operator(Op('⊤')),
            "vdash" => Token::Operator(Op('⊢')),
            "vDash" => Token::Operator(Op('⊨')),
            "Vdash" => Token::Operator(Op('⊩')),
            "models" => Token::Operator(Op('⊨')),
            "slashed" => Token::Slashed,
            command => Token::Command(command.to_owned()),
        }
    }
}
