use super::attribute::{Accent, DisplayStyle, MathVariant, TextTransform};

#[derive(Debug, Clone, PartialEq)]
pub enum Token {
    Illegal(char),
    EOF,
    Begin,
    End,
    Ampersand,
    NewLine,
    Left,
    Right,
    Middle,
    Paren(&'static str),
    LBrace,
    RBrace,
    Frac(Option<DisplayStyle>),
    Underscore,
    Circumflex,
    Binom(Option<DisplayStyle>),
    Overset,
    Underset,
    Overbrace(char),
    Underbrace(char),
    Sqrt,
    Integral(char),
    Lim(&'static str),
    Space(f32),
    Style(TextTransform),
    NormalVariant,
    Big(&'static str),
    Over(char, Accent),
    Under(char, Accent),
    Operator(char),
    BigOp(char),
    Letter(char, MathVariant),
    Number(String),
    Function(&'static str),
    OperatorName,
    Slashed,
    Text,
    Command(String),
}

impl Token {
    pub(crate) fn acts_on_a_digit(&self) -> bool {
        match self {
            Token::Sqrt | Token::Frac(_) | Token::Binom(_) | Token::Style(_) => true,
            _ => false,
        }
    }

    pub fn from_command(command: &str) -> Token {
        match command {
            "mathrm" => Token::NormalVariant,
            "textit" => Token::Style(TextTransform::Italic),
            "mathit" => Token::Style(TextTransform::Italic),
            "textbf" => Token::Style(TextTransform::Bold),
            "mathbf" => Token::Style(TextTransform::Bold),
            "bm" => Token::Style(TextTransform::BoldItalic),
            "symbf" => Token::Style(TextTransform::BoldItalic),
            "mathbb" => Token::Style(TextTransform::DoubleStruck),
            "mathfrak" => Token::Style(TextTransform::Fraktur),
            "mathscr" => Token::Style(TextTransform::Script),
            "mathsf" => Token::Style(TextTransform::SansSerif),
            "texttt" => Token::Style(TextTransform::Monospace),
            "boldsymbol" => Token::Style(TextTransform::BoldItalic),
            "text" => Token::Text,
            "sqrt" => Token::Sqrt,
            "frac" => Token::Frac(None),
            "tfrac" => Token::Frac(Some(DisplayStyle::False)),
            "dfrac" => Token::Frac(Some(DisplayStyle::True)),
            "left" => Token::Left,
            "right" => Token::Right,
            "middle" => Token::Middle,
            "begin" => Token::Begin,
            "end" => Token::End,
            "\\" => Token::NewLine,
            "binom" => Token::Binom(None),
            "tbinom" => Token::Binom(Some(DisplayStyle::False)),
            "dbinom" => Token::Binom(Some(DisplayStyle::True)),
            "overset" => Token::Overset,
            "underset" => Token::Underset,
            "overbrace" => Token::Overbrace('\u{23de}'),
            "underbrace" => Token::Underbrace('\u{23df}'),
            "overparen" => Token::Overbrace('\u{23dc}'),
            "underparen" => Token::Underbrace('\u{23dd}'),
            "overbracket" => Token::Overbrace('\u{23b4}'),
            "underbracket" => Token::Underbrace('\u{23b5}'),
            "!" => Token::Space(-3. / 18.),
            "," => Token::Space(3. / 18.),
            ":" => Token::Space(4. / 18.),
            ";" => Token::Space(5. / 18.),
            " " => Token::Space(1.),
            "quad" => Token::Space(1.),
            "qquad" => Token::Space(2.),
            "langle" => Token::Paren("&lang;"),
            "rangle" => Token::Paren("&rang;"),
            "{" => Token::Paren("{"),
            "}" => Token::Paren("}"),
            "lceil" => Token::Paren("⌈"),
            "rceil" => Token::Paren("⌉"),
            "lfloor" => Token::Paren("⌊"),
            "rfloor" => Token::Paren("⌋"),
            "lgroup" => Token::Paren("⦗"),
            "rgroup" => Token::Paren("⦘"),
            "llbracket" => Token::Paren("⟦"),
            "rrbracket" => Token::Paren("⟧"),
            "lim" => Token::Lim("lim"),
            "liminf" => Token::Lim("lim inf"),
            "limsup" => Token::Lim("lim sup"),
            "min" => Token::Lim("min"),
            "max" => Token::Lim("max"),
            "inf" => Token::Lim("inf"),
            "sup" => Token::Lim("sup"),
            "int" => Token::Integral('∫'),
            "iint" => Token::Integral('∬'),
            "iiint" => Token::Integral('∭'),
            "oint" => Token::Integral('∮'),
            "dot" => Token::Over('\u{02d9}', Accent::True),
            "ddot" => Token::Over('¨', Accent::True),
            "bar" => Token::Over('¯', Accent::True),
            "hat" => Token::Over('^', Accent::True),
            "check" => Token::Over('ˇ', Accent::True),
            "breve" => Token::Over('˘', Accent::True),
            "acute" => Token::Over('´', Accent::True),
            "grave" => Token::Over('`', Accent::True),
            "tilde" => Token::Over('~', Accent::True),
            "vec" => Token::Over('→', Accent::True),
            "overline" => Token::Over('_', Accent::True),
            "underline" => Token::Under('_', Accent::True),
            "widehat" => Token::Over('^', Accent::True),
            "widetilde" => Token::Over('~', Accent::True),
            "overrightarrow" => Token::Over('→', Accent::True),
            "overleftarrow" => Token::Over('←', Accent::True),
            "sum" => Token::BigOp('∑'),
            "prod" => Token::BigOp('∏'),
            "coprod" => Token::BigOp('∐'),
            "bigcap" => Token::BigOp('⋂'),
            "bigcup" => Token::BigOp('⋃'),
            "bigsqcup" => Token::BigOp('⨆'),
            "bigvee" => Token::BigOp('⋁'),
            "bigwedge" => Token::BigOp('⋀'),
            "bigodot" => Token::BigOp('⨀'),
            "bitotimes" => Token::BigOp('⨂'),
            "bigoplus" => Token::BigOp('⨁'),
            "biguplus" => Token::BigOp('⨄'),
            "bigl" => Token::Big("1.2em"),
            "bigr" => Token::Big("1.2em"),
            "Bigl" => Token::Big("1.623em"),
            "Bigr" => Token::Big("1.623em"),
            "biggl" => Token::Big("2.047em"),
            "biggr" => Token::Big("2.047em"),
            "Biggl" => Token::Big("2.470em"),
            "Biggr" => Token::Big("2.470em"),
            // <math xmlns="http://www.w3.org/1998/Math/MathML" display="block">
            //   <semantics>
            //     <mrow>
            //         <mi>a</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="2.470em" minsize="2.470em">(</mo></ mrow>
            //         <mi>b</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="2.047em" minsize="2.047em">(</mo></mrow>
            //         <mi>c</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="1.623em" minsize="1.623em">(</mo></mrow>
            //         <mi>d</mi>
            //         <mrow class="MJX-TeXAtom-OPEN"><mo maxsize="1.2em" minsize="1.2em">(</mo></mrow>
            //         <mi>e</mi>
            //         <mo stretchy="false">(</mo>
            //         <mi>f</mi>
            //         <mo>+</mo>
            //         <mi>g</mi>
            //         <mo stretchy="false">)</mo>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="1.2em" minsize="1.2em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="1.623em" minsize="1.623em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="2.047em" minsize="2.047em">)</mo></mrow>
            //         <mrow class="MJX-TeXAtom-CLOSE"><mo maxsize="2.470em" minsize="2.470em">)</mo></mrow>
            //   </semantics>
            // </math>
            "sin" => Token::Function("sin"),
            "cos" => Token::Function("cos"),
            "tan" => Token::Function("tan"),
            "csc" => Token::Function("csc"),
            "sec" => Token::Function("sec"),
            "cot" => Token::Function("cot"),
            "arcsin" => Token::Function("arcsin"),
            "arccos" => Token::Function("arccos"),
            "arctan" => Token::Function("arctan"),
            "sinh" => Token::Function("sinh"),
            "cosh" => Token::Function("cosh"),
            "tanh" => Token::Function("tanh"),
            "coth" => Token::Function("coth"),
            "exp" => Token::Function("exp"),
            "ln" => Token::Function("ln"),
            "log" => Token::Function("log"),
            "erf" => Token::Function("erf"),
            "erfc" => Token::Function("erfc"),
            "arg" => Token::Function("arg"),
            "ker" => Token::Function("ker"),
            "dim" => Token::Function("dim"),
            "det" => Token::Function("det"),
            "wp" => Token::Function("℘"),
            "operatorname" => Token::OperatorName,
            "Alpha" => Token::Letter('Α', MathVariant::Normal),
            "alpha" => Token::Letter('α', MathVariant::Default),
            "Beta" => Token::Letter('Β', MathVariant::Normal),
            "beta" => Token::Letter('β', MathVariant::Default),
            "Gamma" => Token::Letter('Γ', MathVariant::Normal),
            "gamma" => Token::Letter('γ', MathVariant::Default),
            "digamma" => Token::Letter('ϝ', MathVariant::Default),
            "Delta" => Token::Letter('Δ', MathVariant::Normal),
            "delta" => Token::Letter('δ', MathVariant::Default),
            "Epsilon" => Token::Letter('Ε', MathVariant::Normal),
            "epsilon" => Token::Letter('ϵ', MathVariant::Default),
            "varepsilon" => Token::Letter('ε', MathVariant::Default),
            "Zeta" => Token::Letter('Ζ', MathVariant::Normal),
            "zeta" => Token::Letter('ζ', MathVariant::Default),
            "Eta" => Token::Letter('Η', MathVariant::Normal),
            "eta" => Token::Letter('η', MathVariant::Default),
            "Theta" => Token::Letter('Θ', MathVariant::Normal),
            "theta" => Token::Letter('θ', MathVariant::Default),
            "vartheta" => Token::Letter('ϑ', MathVariant::Default),
            "Iota" => Token::Letter('Ι', MathVariant::Normal),
            "iota" => Token::Letter('ι', MathVariant::Default),
            "Kappa" => Token::Letter('Κ', MathVariant::Normal),
            "kappa" => Token::Letter('κ', MathVariant::Default),
            "Lambda" => Token::Letter('Λ', MathVariant::Normal),
            "lambda" => Token::Letter('λ', MathVariant::Default),
            "Mu" => Token::Letter('Μ', MathVariant::Normal),
            "mu" => Token::Letter('μ', MathVariant::Default),
            "Nu" => Token::Letter('Ν', MathVariant::Normal),
            "nu" => Token::Letter('ν', MathVariant::Default),
            "Xi" => Token::Letter('Ξ', MathVariant::Normal),
            "xi" => Token::Letter('ξ', MathVariant::Default),
            "Omicron" => Token::Letter('Ο', MathVariant::Normal),
            "omicron" => Token::Letter('ο', MathVariant::Default),
            "Pi" => Token::Letter('Π', MathVariant::Normal),
            "pi" => Token::Letter('π', MathVariant::Default),
            "varpi" => Token::Letter('ϖ', MathVariant::Default),
            "Rho" => Token::Letter('Ρ', MathVariant::Normal),
            "rho" => Token::Letter('ρ', MathVariant::Default),
            "varrho" => Token::Letter('ϱ', MathVariant::Default),
            "Sigma" => Token::Letter('Σ', MathVariant::Normal),
            "sigma" => Token::Letter('σ', MathVariant::Default),
            "varsigma" => Token::Letter('ς', MathVariant::Default),
            "Tau" => Token::Letter('Τ', MathVariant::Normal),
            "tau" => Token::Letter('τ', MathVariant::Default),
            "Upsilon" => Token::Letter('Υ', MathVariant::Normal),
            "upsilon" => Token::Letter('υ', MathVariant::Default),
            "Phi" => Token::Letter('Φ', MathVariant::Normal),
            "phi" => Token::Letter('ϕ', MathVariant::Default),
            "varphi" => Token::Letter('φ', MathVariant::Default),
            "Chi" => Token::Letter('Χ', MathVariant::Normal),
            "chi" => Token::Letter('χ', MathVariant::Default),
            "Psi" => Token::Letter('Ψ', MathVariant::Normal),
            "psi" => Token::Letter('ψ', MathVariant::Default),
            "Omega" => Token::Letter('Ω', MathVariant::Normal),
            "omega" => Token::Letter('ω', MathVariant::Default),
            "aleph" => Token::Letter('ℵ', MathVariant::Normal),
            "beth" => Token::Letter('ℶ', MathVariant::Normal),
            "gimel" => Token::Letter('ℷ', MathVariant::Normal),
            "daleth" => Token::Letter('ℸ', MathVariant::Normal),
            "A" => Token::Letter('Å', MathVariant::Normal),
            "a" => Token::Letter('å', MathVariant::Normal),
            "AE" => Token::Letter('Æ', MathVariant::Normal),
            "ae" => Token::Letter('æ', MathVariant::Normal),
            "DH" => Token::Letter('Ð', MathVariant::Normal),
            "dh" => Token::Letter('ð', MathVariant::Normal),
            "dj" => Token::Letter('đ', MathVariant::Normal),
            "L" => Token::Letter('Ł', MathVariant::Normal),
            "l" => Token::Letter('ł', MathVariant::Normal),
            "NG" => Token::Letter('Ŋ', MathVariant::Normal),
            "ng" => Token::Letter('ŋ', MathVariant::Normal),
            "O" => Token::Letter('Ø', MathVariant::Normal),
            "o" => Token::Letter('ø', MathVariant::Normal),
            "OE" => Token::Letter('Œ', MathVariant::Normal),
            "oe" => Token::Letter('œ', MathVariant::Normal),
            "ss" => Token::Letter('ß', MathVariant::Normal),
            "TH" => Token::Letter('Þ', MathVariant::Normal),
            "th" => Token::Letter('þ', MathVariant::Normal),
            "imath" => Token::Letter('ı', MathVariant::Default),
            "jmath" => Token::Letter('ȷ', MathVariant::Default),
            "ell" => Token::Letter('ℓ', MathVariant::Default),
            "hbar" => Token::Letter('ℏ', MathVariant::Default),
            "hslash" => Token::Letter('ℏ', MathVariant::Default),
            "infty" => Token::Letter('∞', MathVariant::Normal),
            "mho" => Token::Letter('℧', MathVariant::Normal),
            "Finv" => Token::Letter('Ⅎ', MathVariant::Normal),
            "Re" => Token::Letter('ℜ', MathVariant::Normal),
            "Im" => Token::Letter('ℑ', MathVariant::Normal),
            "complement" => Token::Letter('∁', MathVariant::Normal),
            "emptyset" => Token::Letter('∅', MathVariant::Normal),
            "therefore" => Token::Letter('∴', MathVariant::Normal),
            "because" => Token::Letter('∵', MathVariant::Normal),
            "Diamond" => Token::Letter('◊', MathVariant::Normal),
            "Box" => Token::Letter('◻', MathVariant::Normal),
            "triangle" => Token::Letter('△', MathVariant::Normal),
            "angle" => Token::Letter('∠', MathVariant::Normal),
            "dagger" => Token::Letter('†', MathVariant::Normal),
            "dag" => Token::Letter('†', MathVariant::Normal),
            "Dagger" => Token::Letter('‡', MathVariant::Normal),
            "ddag" => Token::Letter('‡', MathVariant::Normal),
            "And" => Token::Letter('&', MathVariant::Normal),
            "eth" => Token::Letter('ð', MathVariant::Normal),
            "S" => Token::Letter('§', MathVariant::Normal),
            "P" => Token::Letter('¶', MathVariant::Normal),
            "%" => Token::Letter('%', MathVariant::Normal),
            "_" => Token::Letter('_', MathVariant::Normal),
            "&" => Token::Letter('&', MathVariant::Normal),
            "#" => Token::Letter('#', MathVariant::Normal),
            "$" => Token::Letter('$', MathVariant::Normal),
            "copyright" => Token::Letter('©', MathVariant::Normal),
            "checkmark" => Token::Letter('✓', MathVariant::Normal),
            "circledR" => Token::Letter('Ⓡ', MathVariant::Normal),
            "maltese" => Token::Letter('✠', MathVariant::Normal),
            "colon" => Token::Letter(':', MathVariant::Normal),
            "bigtriangleup" => Token::Letter('△', MathVariant::Normal),
            "sphericalangle" => Token::Letter('∢', MathVariant::Normal),
            "square" => Token::Letter('□', MathVariant::Normal),
            "lozenge" => Token::Letter('◊', MathVariant::Normal),
            "diamondsuit" => Token::Letter('♢', MathVariant::Normal),
            "heartsuit" => Token::Letter('♡', MathVariant::Normal),
            "clubsuit" => Token::Letter('♣', MathVariant::Normal),
            "spadesuit" => Token::Letter('♠', MathVariant::Normal),
            "Game" => Token::Letter('⅁', MathVariant::Normal),
            "flat" => Token::Letter('♭', MathVariant::Normal),
            "natural" => Token::Letter('♮', MathVariant::Normal),
            "sharp" => Token::Letter('♯', MathVariant::Normal),
            "pounds" => Token::Letter('£', MathVariant::Normal),
            "textyen" => Token::Letter('¥', MathVariant::Normal),
            "euro" => Token::Letter('€', MathVariant::Normal),
            "rupee" => Token::Letter('₹', MathVariant::Normal),
            "sun" => Token::Letter('☼', MathVariant::Normal),
            "mercury" => Token::Letter('☿', MathVariant::Normal),
            "venus" => Token::Letter('♀', MathVariant::Normal),
            "earth" => Token::Letter('♁', MathVariant::Normal),
            "mars" => Token::Letter('♂', MathVariant::Normal),
            "jupiter" => Token::Letter('♃', MathVariant::Normal),
            "saturn" => Token::Letter('♄', MathVariant::Normal),
            "uranus" => Token::Letter('♅', MathVariant::Normal),
            "neptune" => Token::Letter('♆', MathVariant::Normal),
            "astrosun" => Token::Letter('☉', MathVariant::Normal),
            "ascnode" => Token::Letter('☊', MathVariant::Normal),
            "times" => Token::Operator('×'),
            "oplus" => Token::Operator('⊕'),
            "ominus" => Token::Operator('⊖'),
            "otimes" => Token::Operator('⊗'),
            "oslash" => Token::Operator('⊘'),
            "odot" => Token::Operator('⊙'),
            "bigcirc" => Token::Operator('◯'),
            "amalg" => Token::Operator('⨿'),
            "pm" => Token::Operator('±'),
            "mp" => Token::Operator('∓'),
            "cdot" => Token::Operator('·'),
            "cdots" => Token::Operator('⋯'),
            "vdots" => Token::Operator('⋮'),
            "ldots" => Token::Operator('…'),
            "ddots" => Token::Operator('⋱'),
            "circ" => Token::Operator('∘'),
            "bullet" => Token::Operator('∙'),
            "star" => Token::Operator('⋆'),
            "div" => Token::Operator('÷'),
            "lnot" => Token::Operator('¬'),
            "land" => Token::Operator('∧'),
            "lor" => Token::Operator('∨'),
            "sim" => Token::Operator('∼'),
            "simeq" => Token::Operator('≃'),
            "nsim" => Token::Operator('≁'),
            "cong" => Token::Operator('≅'),
            "approx" => Token::Operator('≈'),
            "ne" => Token::Operator('≠'),
            "neq" => Token::Operator('≠'),
            "equiv" => Token::Operator('≡'),
            "nequiv" => Token::Operator('≢'),
            "prec" => Token::Operator('≺'),
            "succ" => Token::Operator('≻'),
            "preceq" => Token::Operator('⪯'),
            "succeq" => Token::Operator('⪰'),
            "dashv" => Token::Operator('⊣'),
            "asymp" => Token::Operator('≍'),
            "doteq" => Token::Operator('≐'),
            "propto" => Token::Operator('∝'),
            "barwedge" => Token::Operator('⊼'),
            "ltimes" => Token::Operator('⋉'),
            "rtimes" => Token::Operator('⋊'),
            "Join" => Token::Operator('⋈'),
            "lhd" => Token::Operator('⊲'),
            "rhd" => Token::Operator('⊳'),
            "unlhd" => Token::Operator('⊴'),
            "unrhd" => Token::Operator('⊵'),
            "vee" => Token::Operator('∨'),
            "uplus" => Token::Operator('⊎'),
            "wedge" => Token::Operator('∧'),
            "boxdot" => Token::Operator('⊡'),
            "boxplus" => Token::Operator('⊞'),
            "boxminus" => Token::Operator('⊟'),
            "boxtimes" => Token::Operator('⊠'),
            "boxbox" => Token::Operator('⧈'),
            "boxslash" => Token::Operator('⧄'),
            "boxbslash" => Token::Operator('⧅'),
            "Cap" => Token::Operator('⋒'),
            "Cup" => Token::Operator('⋓'),
            "centerdot" => Token::Operator('∙'),
            "circledast" => Token::Operator('⊛'),
            "circledcirc" => Token::Operator('⊚'),
            "circleddash" => Token::Operator('⊝'),
            "curlyvee" => Token::Operator('⋎'),
            "curlywedge" => Token::Operator('⋏'),
            "dotplus" => Token::Operator('∔'),
            "intercal" => Token::Operator('⊺'),
            "divideontimes" => Token::Operator('⋇'),
            "leftthreetimes" => Token::Operator('⋋'),
            "rightthreetimes" => Token::Operator('⋌'),
            "smallsetminus" => Token::Operator('﹨'),
            "triangledown" => Token::Operator('▽'),
            "triangleleft" => Token::Operator('◁'),
            "triangleright" => Token::Operator('▷'),
            "vartriangle" => Token::Operator('△'),
            "veebar" => Token::Operator('⊻'),
            "cap" => Token::Operator('∩'),
            "cup" => Token::Operator('∪'),
            "mid" => Token::Operator('\u{2223}'),
            "nmid" => Token::Operator('\u{2224}'),
            "|" => Token::Paren("\u{2225}"),
            "parallel" => Token::Operator('∥'),
            "perp" => Token::Operator('⊥'),
            "forall" => Token::Operator('∀'),
            "exists" => Token::Operator('∃'),
            "nexists" => Token::Operator('∄'),
            "lt" => Token::Operator('<'),
            "gt" => Token::Operator('>'),
            "leq" => Token::Operator('≤'),
            "geq" => Token::Operator('≥'),
            "ll" => Token::Operator('≪'),
            "gg" => Token::Operator('≫'),
            "lessapprox" => Token::Operator('⪅'),
            "lesssim" => Token::Operator('≲'),
            "eqslantless" => Token::Operator('⪕'),
            "leqslant" => Token::Operator('⩽'),
            "leqq" => Token::Operator('≦'),
            "geqq" => Token::Operator('≧'),
            "geqslant" => Token::Operator('⩾'),
            "eqslantgtr" => Token::Operator('⪖'),
            "gtrsim" => Token::Operator('≳'),
            "gtrapprox" => Token::Operator('⪆'),
            "approxeq" => Token::Operator('≊'),
            "lessdot" => Token::Operator('⋖'),
            "lll" => Token::Operator('⋘'),
            "lessgtr" => Token::Operator('≶'),
            "lesseqgtr" => Token::Operator('⋚'),
            "lesseqqgtr" => Token::Operator('⪋'),
            "doteqdot" => Token::Operator('≑'),
            "risingdotseq" => Token::Operator('≓'),
            "leftarrow" => Token::Operator('←'),
            "gets" => Token::Operator('←'),
            "rightarrow" => Token::Operator('→'),
            "to" => Token::Operator('→'),
            "nleftarrow" => Token::Operator('↚'),
            "nrightarrow" => Token::Operator('↛'),
            "leftrightarrow" => Token::Operator('↔'),
            "nleftrightarrow" => Token::Operator('↮'),
            "longleftarrow" => Token::Operator('⟵'),
            "longrightarrow" => Token::Operator('⟶'),
            "longleftrightarrow" => Token::Operator('⟷'),
            "Leftarrow" => Token::Operator('⇐'),
            "Rightarrow" => Token::Operator('⇒'),
            "nLeftarrow" => Token::Operator('⇍'),
            "nRightarrow" => Token::Operator('⇏'),
            "Leftrightarrow" => Token::Operator('⇔'),
            "nLeftrightarrow" => Token::Operator('⇎'),
            "Longleftarrow" => Token::Operator('⟸'),
            "impliedby" => Token::Operator('⟸'),
            "Longrightarrow" => Token::Operator('⟹'),
            "implies" => Token::Operator('⟹'),
            "Longleftrightarrow" => Token::Operator('⟺'),
            "iff" => Token::Operator('⟺'),
            "uparrow" => Token::Operator('↑'),
            "downarrow" => Token::Operator('↓'),
            "updownarrow" => Token::Operator('↕'),
            "Uparrow" => Token::Operator('⇑'),
            "Downarrow" => Token::Operator('⇓'),
            "Updownarrow" => Token::Operator('⇕'),
            "nearrow" => Token::Operator('↗'),
            "searrow" => Token::Operator('↘'),
            "swarrow" => Token::Operator('↙'),
            "nwarrow" => Token::Operator('↖'),
            "rightharpoonup" => Token::Operator('⇀'),
            "rightharpoondown" => Token::Operator('⇁'),
            "leftharpoonup" => Token::Operator('↼'),
            "leftharpoondown" => Token::Operator('↽'),
            "upharpoonleft" => Token::Operator('↿'),
            "upharpoonright" => Token::Operator('↾'),
            "downharpoonleft" => Token::Operator('⇃'),
            "downharpoonright" => Token::Operator('⇂'),
            "rightleftharpoons" => Token::Operator('⇌'),
            "leftrightharpoons" => Token::Operator('⇋'),
            "curvearrowleft" => Token::Operator('↶'),
            "circlearrowleft" => Token::Operator('↺'),
            "Lsh" => Token::Operator('↰'),
            "upuparrows" => Token::Operator('⇈'),
            "rightrightarrows" => Token::Operator('⇉'),
            "rightleftarrows" => Token::Operator('⇄'),
            "Rrightarrow" => Token::Operator('⇛'),
            "rightarrowtail" => Token::Operator('↣'),
            "looparrowright" => Token::Operator('↬'),
            "curvearrowright" => Token::Operator('↷'),
            "circlearrowright" => Token::Operator('↻'),
            "Rsh" => Token::Operator('↱'),
            "downdownarrows" => Token::Operator('⇊'),
            "leftleftarrows" => Token::Operator('⇇'),
            "leftrightarrows" => Token::Operator('⇆'),
            "Lleftarrow" => Token::Operator('⇚'),
            "leftarrowtail" => Token::Operator('↢'),
            "looparrowleft" => Token::Operator('↫'),
            "mapsto" => Token::Operator('↦'),
            "longmapsto" => Token::Operator('⟼'),
            "hookrightarrow" => Token::Operator('↪'),
            "hookleftarrow" => Token::Operator('↩'),
            "multimap" => Token::Operator('⊸'),
            "leftrightsquigarrow" => Token::Operator('↭'),
            "rightsquigarrow" => Token::Operator('⇝'),
            "lightning" => Token::Operator('↯'),
            "Yleft" => Token::Operator('⤙'),
            "Yright" => Token::Operator('⤚'),
            "in" => Token::Operator('\u{2208}'),
            "ni" => Token::Operator('\u{2209}'),
            "notin" => Token::Operator('\u{2209}'),
            "subset" => Token::Operator('\u{2282}'),
            "supset" => Token::Operator('\u{2283}'),
            "subseteq" => Token::Operator('\u{2286}'),
            "supseteq" => Token::Operator('\u{2287}'),
            "nsubseteq" => Token::Operator('\u{2288}'),
            "nsupseteq" => Token::Operator('\u{2289}'),
            "subsetneq" => Token::Operator('\u{228a}'),
            "supsetneq" => Token::Operator('\u{228b}'),
            "sqsubset" => Token::Operator('⊏'),
            "sqsubseteq" => Token::Operator('⊑'),
            "sqsupset" => Token::Operator('⊐'),
            "sqsupseteq" => Token::Operator('⊒'),
            "sqcap" => Token::Operator('⊓'),
            "sqcup" => Token::Operator('⊔'),
            "setminus" => Token::Operator('∖'),
            "partial" => Token::Operator('∂'),
            "nabla" => Token::Operator('∇'),
            "smile" => Token::Operator('⌣'),
            "from" => Token::Operator('⌢'),
            "wr" => Token::Operator('≀'),
            "bot" => Token::Operator('⊥'),
            "top" => Token::Operator('⊤'),
            "vdash" => Token::Operator('⊢'),
            "vDash" => Token::Operator('⊨'),
            "Vdash" => Token::Operator('⊩'),
            "models" => Token::Operator('⊨'),
            "slashed" => Token::Slashed,
            command => Token::Command(command.to_owned()),
        }
    }
}
