name: Clippy check

on:
  pull_request:
    branches: ["main"]

jobs:
  clippy_check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      - uses: actions-rust-lang/setup-rust-toolchain@a0b538fa0b742a6aa35d6e2c169b4bd06d225a98 # v1.15.3
        with:
          toolchain: nightly
          components: clippy
      - uses: clechasseur/rs-clippy-check@v6.0.0
        with:
          args: --all --all-features
        env:
          RUSTFLAGS: ""
