name: CI

on:
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: actions/setup-node@v5
      with:
        node-version: latest
    - working-directory: nodejs
      run: npm install
    - working-directory: nodejs
      run: npm run build
    - working-directory: nodejs
      run: npm test
      
