name: Publish Package to npmjs
on:
  release:
    types: [published]

permissions:
  id-token: write # Required for OIDC
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v7
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v7
        with:
          node-version: latest
          registry-url: "https://registry.npmjs.org"
      # Ensure npm 11.5.1 or later is installed
      - name: Update npm
        run: npm install -g npm@latest
      - working-directory: nodejs
        run: npm install
      - name: Install wasm target
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Get wasm-bindgen version
        id: wasm-bindgen-version
        run: |
          VERSION=$(grep -A 1 'name = "wasm-bindgen"' Cargo.lock | grep version | sed 's/.*"\(.*\)".*/\1/')
          echo "version=$VERSION" >> $GITHUB_OUTPUT
      - name: Install wasm-bindgen-cli
        uses: taiki-e/install-action@v2
        with:
          tool: wasm-bindgen-cli@${{ steps.wasm-bindgen-version.outputs.version }}
      - name: Build the wasm module
        working-directory: nodejs
        run: |
          npm run build
      - name: Run the tests
        working-directory: nodejs
        run: |
          npm test
      - run: npm publish
        working-directory: nodejs
